version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - aws cloudformation package --s3-bucket codepipeline-us-west-2-577660647740 --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - cfntemplate.yaml
    - outputtemplate.yaml